version: "3.3"
services:
  lobby:
    environment:
      - NODE_ENV=development
    volumes:
      - client:/app/lobby/public
  node:
    environment:
      - NODE_ENV=development
  redis:
    image: redis
volumes:
  client:
