version: "3.3"
services:
  lobby:
    restart: always
    build:
      context: .
    image: throneteki_lobby
    ports:
      - "4000:4000"
      - "9229:9229"
    links:
      - mongo
    depends_on:
      - mongo
    command:
      - node
      - "--inspect=0.0.0.0"
      - "."
    environment:
      - NODE_ENV=development
    volumes:
      - client:/app/lobby/public
  node1:
    restart: always
    build:
      context: .
      dockerfile: ./server/gamenode/Dockerfile
    image: throneteki_node
    ports:
      - "9500:9500"
      - "9339:9339"
    command:
      - node
      - "--inspect=0.0.0.0:9339"
      - "server/gamenode"
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
  redis:
    image: redis
volumes:
  mongodb:
  client:
  
